// GENERATED by scripts/control-plane/generate-frozen-surfaces.mjs — do not edit.
// Route -> the frozen execution paths that route's components mutate. Regenerate
// after any change to the freeze manifest or to a component's mutation calls:
//   npm run control-plane:frozen-surfaces

export const FROZEN_EXECUTION_SURFACES: Readonly<Record<string, readonly string[]>> = {
  "/agent-kanban": ["/api/agent-kanban/build", "/api/agent-kanban/plan", "/api/seo/deploy"],
  "/antigravity": ["/api/antigravity/chat"],
  "/apps": ["/api/appslab/run", "/api/appslab/stop"],
  "/astros": ["/api/astros/notebook", "/api/astros/scan", "/api/radar/publish"],
  "/deepseek-coder": ["/api/dscoder/chat"],
  "/engine": ["/api/local-hermes/run"],
  "/freeclaude": ["/api/freeclaude/build", "/api/freeclaude/chat"],
  "/fusion": ["/api/fusion/chat"],
  "/games": ["/api/games/commission"],
  "/glm": ["/api/glm/chat"],
  "/glm-code": ["/api/glm-code/build"],
  "/grok": ["/api/grok/chat"],
  "/hermes": ["/api/hermes/chat"],
  "/higgsfield": ["/api/higgs/run"],
  "/hy3-coder": ["/api/hy3coder/chat"],
  "/jcode": ["/api/jcode/build"],
  "/kanban": ["/api/hermes/kanban/action", "/api/hermes/kanban/dispatch"],
  "/kimi": ["/api/kimi/chat"],
  "/leads": ["/api/leads/enrich", "/api/leads/find", "/api/leads/icp", "/api/leads/score"],
  "/local": ["/api/local/chat"],
  "/loop": ["/api/loop/run"],
  "/muse-code": ["/api/musecoder/chat"],
  "/music": ["/api/music/generate"],
  "/notebook": ["/api/notebooklm/artifact/download", "/api/notebooklm/ask", "/api/notebooklm/notebooks", "/api/notebooklm/research", "/api/notebooklm/research/import", "/api/notebooklm/shortvideo", "/api/notebooklm/studio"],
  "/omniroute": ["/api/omniroute/chat"],
  "/openclaw": ["/api/openclaw/chat"],
  "/opencode": ["/api/opencode/build"],
  "/opendesign": ["/api/opendesign/control", "/api/opendesign/projects"],
  "/openmontage": ["/api/openmontage/generate"],
  "/pipeline": ["/api/pipeline/build", "/api/pipeline/decide", "/api/pipeline/shape"],
  "/radar": ["/api/hermes/tts", "/api/radar/draft", "/api/radar/publish", "/api/radar/scan"],
  "/room": ["/api/room"],
  "/ruflo": ["/api/ruflo/swarm"],
  "/sakana": ["/api/sakana/chat"],
  "/seo": ["/api/seo/deploy", "/api/seo/generate", "/api/seo/parasite", "/api/seo/research"],
  "/studio": ["/api/hermes/media"],
  "/thumbnails": ["/api/thumbnails/generate", "/api/thumbnails/research"],
  "/video": ["/api/hermes/studio/generate", "/api/video/auto/assemble", "/api/video/auto/script", "/api/video/heygen/generate", "/api/video/hyperframes/init", "/api/video/hyperframes/keyframes", "/api/video/hyperframes/render"],
  "/video-use": ["/api/videouse/run"],
};

export function frozenPathsForRoute(pathname: string): readonly string[] {
  return FROZEN_EXECUTION_SURFACES[pathname] ?? [];
}
